name: Challenge 2

on: push

env: 
  ARTIFACT_NAME: myartifact

jobs:
  main:
    name: First job
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Upload the artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME}} 
          path: ./artifacts

