name: First workflow

on: 
  push:
    branches: [ "main" ]

jobs:
  job1: 
    name: First job
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps:
      - name: Step two
        uses: env | sort

  job2:
    name: Second job
    runs-on: windows-latest
    steps:
      - name: Step two
        uses: "Get-ChildItem Env: | Sort-Object Name"

